// pipeline {
//     agent { label 'WORKSTATION'}
//
//     stages {
//         stage('ansible playbook run') {
//             steps {
//                 sh 'ansible-playbook 04-tags.yml'
//             }
//         }
//     }
// }
pipeline {
    agent

    stages {
        stage('Stage1') {
            steps {
              sh 'echo  Hello World'
            }
        }
    }
}