- name: Play Level Variable
  hosts: all
  vars:
    URL: www.example.com
    a: 100000
  tasks:
    - name: print variable at task1
      ansible.builtin.debug:
        msg: URL = {{URL}}
    - name: print variable at task2
      ansible.builtin.debug:
        msg: a = {{a}}, {{URL}}
 - name: Play for Variable from file
   hosts: all
   vars_file:
     - sample-vars.yml
    tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL- {{URL}}
