- name: Play Level Variable
  hosts: all
  vars:
    URL: www.example.com
    a: 100000
  tasks:
    - name: print variable at task1
      ansible.builtin.debug:
        msg: URL = {{URL}}
    - name: print variable at task2
      ansible.builtin.debug:
        msg: a = {{a}}, {{URL}}

- name: Play for Variable from file
  hosts: all
  vars_files:
     - sample-vars.yml
  tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL- {{URL}}

# Task level variable
- name: Play for task level variable
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: www.task1.com
    - name: task2
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: www.task2.com
#Inventory Level Variable
- name: Inventory variable access
  hosts: all
  tasks:
    - name: task accessing inv var
      ansible.builtin.debug:
        msg: "{{URL}}"
# Command Line variable
- name: Play for command line var
  hosts: all
  tasks:
    - name: task with cmd line var
      ansible.builtin.debug:
        msg: "{{URL}}"
