- name: Demo on tags
  hosts: localhost
  tasks:
    - name: tasks from catalogue
      debug:
        msg: Hello from catalogue
      tags: catalogue

    - name: tasks from frontend
      debug:
          msg: Hello from frontend
      tags: frontend