- name: frontend setup
  hosts: frontend
  become: yes
  tags: frontend
  roles:
    - frontend

- name: mongodb setup
  hosts: mongodb
  become: yes
  tags: mongodb
  roles:
    - mongodb

- name: catalogue setup
  hosts: catalogue
  become: yes
  tags: catalogue
  roles:
    - catalogue

- name: redis setup
  hosts: redis
  become: yes
  tags: redis
  roles:
    - redis

- name: user setup
  hosts: user
  become: yes
  tags: user
  roles:
    - user

- name: cart setup
  hosts: cart
  become: yes
  tags: cart
  roles:
    - cart

- name: mysql setup
  hosts: mysql
  become: yes
  tags: mysql
  roles:
    - mysql
